name: stability
channels:
  - conda-forge
  - pytorch
dependencies:
  - captum
  - cmcrameri
  - datasets
  - hydra-core
  - ipykernel
  - libgcc-ng
  - libstdcxx-ng
  - matplotlib
  - numpy
  - omegaconf
  - packaging
  - pacmap
  - pandas
  - pip
  - plotly
  - polars>=0.20
  - psutil
  - pyarrow
  - python=3.11
  - pytorch>=2.5
  - pytorch-cuda=12.1
  - scikit-learn
  - scipy
  - seaborn
  - sentencepiece
  - spacy
  - statsmodels
  - tqdm
  - transformers>=4.48
  - umap-learn
  - pip:
    - accelerate==1.10.1
    - astor==0.8.1
    - bidict==0.23.1
    - category_encoders==2.8.1
    - cvxopt==1.3.2
    - h11==0.16.0
    - inflect==7.5.0
    - misvm==1.0
    - more-itertools==10.8.0
    - mrmr-selection==0.2.8
    - nnsight==0.5.4
    - numba==0.61.0
    - pacmap==0.8.0
    - protobuf==6.32.1
    - python-engineio==4.12.2
    - python-socketio==5.13.0
    - simple-websocket==1.1.0
    - sympy==1.13.1
    - toml==0.10.2
    - typeguard==4.4.4
    - websocket-client==1.8.0
    - wsproto==1.2.0
