defaults:
  - base
  - _self_

name: cities_loc
noise_prefix: cities_loc_noise

datasets: ['cities_loc_true_false', 'cities_loc_synthetic']
datasets_fictional: ['cities_loc_fictional']
datasets_noise: ['cities_loc_noise_10']
datasets_test: []
agg: full

use_fictional: true
use_noise: true