defaults:
  - base_llama
  - _self_

name: _mistral-7B-v0.3
model: mistralai/Mistral-7B-Instruct-v0.3
layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
instruct: True

task_layers:
  cities_loc: 19
  med_indications: 21
  defs: 18