defaults:
  - base_llama
  - _self_

name: _qwen-2.5-7b
model: Qwen/Qwen2.5-7B-Instruct
layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]
instruct: True

task_layers:
  cities_loc: 19
  med_indications: 21
  defs: 18