model: ???
name: ???
token: INSERT_ACCESS_TOKEN # HugginFace Token (can abtain from https://huggingface.co/settings/tokens)
module: model
encoders: layers
submodule_att: self_attn
submodule_mlp: mlp
submodule_norm: norm
submodule_head: lm_head
layers: []
instruct: False
dtype: float32
system_role: user
user_role: user
assist_role: model
end_token: '<end_of_turn>'