defaults:
  - base_gemma
  - _self_

name: gemma-7b
model: google/gemma-7b
layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]
instruct: False

task_layers:
  cities_loc: 14
  med_indications: 19
  defs: 17