defaults:
  - base_llama
  - _self_

name: llama-3.2-3b
model: meta-llama/Llama-3.2-3B
layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]

task_layers:
  cities_loc: 16
  med_indications: 17
  defs: 15