defaults:
  - base_llama
  - _self_

name: llama-3-8b
model: meta-llama/Meta-Llama-3-8B
layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
instruct: False

task_layers:
  cities_loc: 18
  med_indications: 17
  defs: 17